### ISSUE TITLE
[Bug] Package dependency issue

### ISSUE THREAD

**Issue by Aperjump** [yutiansut/QUANTAXIS#749]
**Describe the bug**

Under **pip 18.0** python3, I encountered an error when installing one dependent package `jupyter-echarts-pypkg==0.1.0`. Below is my error message: 
---------------------------------
```
Collecting jupyter-echarts-pypkg==0.1.0 (from pyecharts==0.4.1->quantaxis==1.0.69.dev3)
  Downloading https://files.pythonhosted.org/packages/ed/1e/856f74b4a37637fdaa9abb7e6bdafd07b9f305fa0a07b8c46b58a0bf65d6/jupyter-echarts-pypkg-0.1.0.tar.gz (514kB)
    100% |████████████████████████████████| 522kB 4.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/dr/9vhdr01x14x3p71yv_yjr3rr0000gn/T/pip-install-8znmdwep/jupyter-echarts-pypkg/setup.py", line 8, in <module>
        from pyecharts_jupyter_installer import install_cmd_for
    ModuleNotFoundError: No module named 'pyecharts_jupyter_installer'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dr/9vhdr01x14x3p71yv_yjr3rr0000gn/T/pip-install-8znmdwep/jupyter-echarts-pypkg/setup.py", line 13, in <module>
        pip.main(['install', 'pyecharts-jupyter-installer'])
    AttributeError: module 'pip' has no attribute 'main'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/dr/9vhdr01x14x3p71yv_yjr3rr0000gn/T/pip-install-8znmdwep/jupyter-echarts-pypkg/
```
**To Reproduce**
```
mkvirtualenv quantenv
workon quantenv
cd /path-to-quantaxis/
pip --no-cache-dir -e .
```

**Expected behavior**
The error relates to `pyecharts` package, and I find [!this](https://github.com/pyecharts/pyecharts/issues/492) issue in pyecharts discussion. 
When I upgrade my `pyecharts` package to 0.5.6, the bug disappears.  

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] Python 3.6.5 :: Anaconda, Inc. pip 18.0

**Comment by yutiansut** [comment]
cause the pip 10+ has change the api of main, so please first downgrade the pip version and install

using

```
pip install pip==9.0.1
pip install jupyter-echarts-pypkg
pip install quantaxis 

```

thx

**Comment by yutiansut** [comment]
cause the pip 10+ has change the api of main, so please first downgrade the pip version and install
@Aperjump 
using

```
pip install pip==9.0.1
pip install jupyter-echarts-pypkg
pip install quantaxis 

```

thx

**Comment by yutiansut** [comment]
after the quantaxis install

if U meet the 'time out' parameter while saving data, pls  take a look at [TIME OUT Solution](https://github.com/QUANTAXIS/QUANTAXIS/issues/747)
